  name: Waka Readme

  on:
    schedule:
      # Runs at 12am IST
      - cron: '30 18 * * *'
    workflow_dispatch:
  jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@v2.6.1
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            SHOW_TITLE: false
            SHOW_EDITORS: false
            SHOW_PROJECTS: false
            SHOW_OS: true
            SHOW_LANGUAGES: true
            SHOW_WEEKLY_COMMIT: false
            SHOW_TIMEZONE: false
            SHOW_LOC_CHART: false
